title: My blog
author: Arya R N
email: aryakunjamma@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"

github_username: ranilakshmi # DO NOT include the @ character, or else the build will fail!
show_excerpts: true # set to false to remove excerpts on the homepage